name: Check Alerts

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Alert Check Function
        run: |
          curl -X POST "${{ secrets.SUPABASE_FUNCTIONS_URL }}/check-alerts" \
          -H "Authorization: Bearer ${{ secrets.CHECK_ALERTS_SECRET }}" \
          -H "Content-Type: application/json"
